# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ecaea0b55df762236be5e0ce752bea37d1b8c604a16dd607702a1c518cc902ce3b932ce352ec7eafda7ad107bc62db16a3e16e145a2e6791c47f157a7d48f039

test:
  secret_key_base: 65479e3fc8dad21651bec3b0a87603dc0751a2d77e55e677720f0ad2b9cd0f47bfaf3a3e1063adaee0030f6dc6a7eabbf61de688e38897e58a74b8a1e38b2eef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
